src/main/java/hu/dpc/phee/operator/entity/transactionrequest/TransactionRequest.java
src/main/java/hu/dpc/phee/operator/importer/VariableParser.java

This PR includes below major changes
1. Updated `transactionRequest` DTO with new `externalId` field.
2. Added parsing of new variable `externalId` to `externalId` field of `transactionRequest`".

Added mpesaReceiptNumber parsing

---

src/main/java/hu/dpc/phee/operator/importer/KafkaConsumer.java

Improved existing error log statement for better insights.

Added debug level log for better monitoring of bugs

---

src/main/java/hu/dpc/phee/operator/importer/InflightTransactionRequestManager.java
src/main/java/hu/dpc/phee/operator/importer/KafkaConsumer.java
src/main/java/hu/dpc/phee/operator/importer/RecordParser.java
src/main/java/hu/dpc/phee/operator/importer/TempDocumentStore.java

Delete document for workflow key

---

src/main/java/hu/dpc/phee/operator/entity/batch/Batch.java
src/main/java/hu/dpc/phee/operator/importer/RecordParser.java
src/main/java/hu/dpc/phee/operator/importer/VariableParser.java
src/main/resources/application.yml

This PR includes the below updates
1. Updated `batches` table with `SUB_BATCH_ID` field.
2. Added support for multiple variable parsing in `batchParser`.
3. Fixed configuration for SLCB BPMN.
4. Added amount related variable parsing

Improved variable parsing to support subBatches and transactionCount related variables

---

src/main/java/hu/dpc/phee/operator/importer/VariableParser.java

Added new variable parsing for populating result file in batch table.

Added new variable in batch variable parser

---

build.gradle
src/main/java/hu/dpc/phee/operator/DatabaseImporterApplication.java
src/main/java/hu/dpc/phee/operator/config/AwsStorageConfig.java
src/main/java/hu/dpc/phee/operator/entity/batch/CsvSchema.java
src/main/java/hu/dpc/phee/operator/entity/batch/Transaction.java
src/main/java/hu/dpc/phee/operator/file/AwsFileTransferImpl.java
src/main/java/hu/dpc/phee/operator/file/FileTransferService.java
src/main/java/hu/dpc/phee/operator/importer/KafkaConsumer.java
src/main/java/hu/dpc/phee/operator/importer/RecordParser.java
src/main/java/hu/dpc/phee/operator/importer/TempDocumentStore.java
src/main/java/hu/dpc/phee/operator/util/BatchFormatToTransferMapper.java
src/main/resources/application.yml

Highlights of this PR
1. Implements logic for adding data into transfers table from CSV. **(TESTED)**

Csv to transfer

---

src/main/java/hu/dpc/phee/operator/entity/batch/Batch.java
src/main/java/hu/dpc/phee/operator/entity/batch/Transaction.java
src/main/java/hu/dpc/phee/operator/importer/VariableParser.java
src/main/java/hu/dpc/phee/operator/util/BatchFormatToTransferMapper.java

Update in this PR
1. Updated `batches` DTO to support payment mode.
2. Added support for parsing new zeebe variable `paymentMode`.
3. Updated Transaction.java DTO, as per the latest API spec.

Added variable parsing for paymentMode

---

src/main/java/hu/dpc/phee/operator/importer/RecordParser.java
src/main/java/hu/dpc/phee/operator/util/BatchFormatToTransferMapper.java

Changes in this PR
1. Populated missing fields in `transfer` table.

Fix for transfers table null data

---

src/main/resources/application.yml

Security fix

---

src/main/java/hu/dpc/phee/operator/importer/RecordParser.java
src/main/resources/application.yml

* Fix for issue where gsma p2p workflow is not getting pushed to transfer table in database.
* Added more meaningful error message for same issue.

Fix for gsma p2p workflow not populating in db

---

src/main/java/hu/dpc/phee/operator/entity/transactionrequest/TransactionRequest.java
src/main/java/hu/dpc/phee/operator/importer/RecordParser.java
src/main/java/hu/dpc/phee/operator/importer/VariableParser.java
src/main/java/hu/dpc/phee/operator/util/BatchFormatToTransferMapper.java

* Security fixes
* TransactionId not pupulating in case of bulk disbursment hotfix.
* Added variable parsing for errorInformation field for trasnactionRequest.

Multiple fixes

---

src/main/resources/application.yml

Fixed PHEE-177

---

src/main/resources/application.yml

- added id,direction and type for paybill workflow
- populating MySQL table for tenants
@fynmanoj @avikganguly01

Added id for paybill workflow

---

src/main/resources/application.yml

Added BPMN created for [GOV-338](https://mifosforge.jira.com/browse/GOV-338) for making sure date gets pushed into rdbms
[GOV-338]: https://mifosforge.jira.com/browse/GOV-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOV-338: Adding bpmn name for operation transparency

---

src/main/resources/application.yml

Adding bpmn for inserting workflow for mock payment transfer with debit related data into database 

GOV-150: Updated bpmn in importer for storage

---

src/main/resources/application.yml

Bpmn added for:
Debulking to APIs for Txn having mock events in implementation. Those mock events are transfer (polling, callback) and account lookup (polling, callback). Destination tenant variable saved as Zeebe variable debulkingDFSPID (same variable as closed loop bulk connector and documented in READMEs) Workflow names :- MinimalMockFundTransfer, MockFundTransferWithAccountLookup. (+1)
Related Pr: https://github.com/openMF/ph-ee-connector-channel/pull/100

Adding new bpmn for minimal mock fund transfer

---

src/main/java/hu/dpc/phee/operator/importer/RecordParser.java
src/main/resources/application.yml

[GOV-508](https://mifosforge.jira.com/browse/GOV-508)
[GOV-508]: https://mifosforge.jira.com/browse/GOV-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOV-508: Importer rdbms bulk parser configuration

---

src/main/java/hu/dpc/phee/operator/entity/outboundmessages/OutboudMessages.java
src/main/java/hu/dpc/phee/operator/entity/outboundmessages/OutboundMessagesRepository.java
src/main/java/hu/dpc/phee/operator/importer/InflightOutboundMessageManager.java
src/main/java/hu/dpc/phee/operator/importer/KafkaConsumer.java
src/main/java/hu/dpc/phee/operator/importer/RecordParser.java
src/main/java/hu/dpc/phee/operator/importer/VariableParser.java
src/main/java/hu/dpc/phee/operator/util/SmsMessageStatusType.java
src/main/resources/application.yml

[PHEE-369 Add outbound message parser in importer-rdbms](https://fynarfin.atlassian.net/browse/PHEE-369?atlOrigin=eyJpIjoiNGEwYjMwODA0MGFhNGMwNmIyN2RmMGY5YjU1ODZmYjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

PHEE-369 Add outbound message parser in importer-rdbms

---

.circleci/config.yml

(https://mifosforge.jira.com/browse/GOV-527) Description
* Added CircleCI to build and push docker image to docker hub
* Add a link to the design document or include the design bullet points related to this PR here.

#GOV-527  Build and Push Docker Image to Docker Hub

---

build.gradle
src/main/java/hu/dpc/phee/operator/entity/batch/Batch.java
src/main/java/hu/dpc/phee/operator/importer/VariableParser.java

* Added logic to parse registeringInstituteId, payerIdentifier & clientCorrelationId
* Added lambok
* Removed boilerplate from Batch POJO.
[GOV-223](https://mifosforge.jira.com/browse/GOV-223)
[GOV-223]: https://mifosforge.jira.com/browse/GOV-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOV-223 Added logic to parse registeringInstituteId, payerIdentifier & clientCorrelationId

---

build.gradle
src/main/resources/application.yml

(https://mifosforge.jira.com/browse/GOV-134)
Added Liveness and readiness probes to Application yaml
Added actuators dependency in gradle file

GOV-134 Enable liveness and readiness

---

build.gradle
src/main/resources/application.yml

Reverts openMF/ph-ee-importer-rdbms#54

Revert "GOV-134 Enable liveness and readiness"

---

src/main/resources/application.yml

[PHEE-422 Create minimalMockTransferRequest BPMN, its workers, required configurations, integration test](https://fynarfin.atlassian.net/browse/PHEE-422?atlOrigin=eyJpIjoiOGZlZTE1MTBjOGVmNDhjMTg3ODEyMWI5MjU2M2NiNDAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

PHEE-422 added bpmn minimal_mack_transfer_request

---

src/main/resources/application.yml

GOV-517 Adding minimal mock fund transfer account lookup bpmn

---

src/main/java/hu/dpc/phee/operator/importer/VariableParser.java

* Update the zeebe variable in batchParser
[GOV-325](https://mifosforge.jira.com/browse/GOV-325)
[GOV-325]: https://mifosforge.jira.com/browse/GOV-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Patch-GOV-325: Fixed the batchParser

---

.circleci/config.yml

[PHEE-477 Create an orb that fetches the docker images and do helm upgrade](https://fynarfin.atlassian.net/browse/PHEE-477?atlOrigin=eyJpIjoiNGU2MjVhNjJjZjg0NGRhMjk4ZjM4Yzg3OGVkZmMzYzEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

[phee-477]fix for docker build

---

src/main/java/hu/dpc/phee/operator/config/AwsStorageConfig.java
src/main/resources/application.yml

[PHEE-494 Add Minio to the ph ee engine helm chart](https://fynarfin.atlassian.net/browse/PHEE-494?atlOrigin=eyJpIjoiZjQ4MjNhZmJmZTdlNDEyZGJhNTAyYzE0MjcyZjkwMWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

[PHEE-494] Add Minio to the ph ee engine helm chart

---

src/main/resources/application.yml

* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.

[GOV-324] Adding bpmn

---

.circleci/config.yml
src/main/java/hu/dpc/phee/operator/config/AwsStorageConfig.java
src/main/java/hu/dpc/phee/operator/entity/transfer/Transfer.java
src/main/java/hu/dpc/phee/operator/file/CsvFileService.java
src/main/java/hu/dpc/phee/operator/streams/InflightBatchManager.java
src/main/java/hu/dpc/phee/operator/streams/RecordParser.java
src/main/resources/application-local.yml
src/main/resources/application-tenants.yml
src/main/resources/application.yml

* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.

[G2PCCODV-50] include Gov-360, Gov-325 update

---

src/main/java/hu/dpc/phee/operator/streams/RecordParser.java

[PHEE-619] payer fsp fix

---

src/main/resources/application-local.yml

[GOV-83A] Adding bill pay bpmn in application

---

src/main/resources/application-local.yml

[GOV-83B] Adding bpmn

---

src/main/resources/application-local.yml

[PHEE-638] adding payeedfsp id variable

---

src/main/java/hu/dpc/phee/operator/entity/transactionrequest/TransactionRequestState.java
src/main/java/hu/dpc/phee/operator/streams/RecordParser.java
src/main/resources/application-local.yml

[GOV-83C] RTP transaction state fix

---

src/main/java/hu/dpc/phee/operator/entity/tenant/ThreadLocalContextUtil.java
src/main/java/hu/dpc/phee/operator/streams/InFlightTransferManager.java
src/main/java/hu/dpc/phee/operator/streams/InflightBatchManager.java
src/main/java/hu/dpc/phee/operator/streams/RecordParser.java
src/main/java/hu/dpc/phee/operator/streams/StreamsSetup.java

Hikaripool issue fix
Updated handling of incident, instead of creating new txns should update existing

[PHEE-641] Hikaripool issue fix

---

src/main/java/hu/dpc/phee/operator/entity/transfer/Transfer.java
src/main/java/hu/dpc/phee/operator/streams/InflightBatchManager.java

[PHEE-646] add tenant variable

---

src/main/resources/application-local.yml

[bulkfix] Fix bulk processor account lookup flow

---

src/main/java/hu/dpc/phee/operator/streams/InflightBatchManager.java
src/main/java/hu/dpc/phee/operator/streams/RecordParser.java
src/main/java/hu/dpc/phee/operator/util/PaymentModeEnum.java

[PHEE-675] Closedloop Fix

---

src/main/java/hu/dpc/phee/operator/streams/InflightBatchManager.java
src/main/resources/application-local.yml

[PHEE-697] Populating payee dfsp id for payerFundTransfer flow
